/** Pure, deterministic raster preparation for preview and CAM planning. */
export type RasterDither = "threshold" | "grayscale" | "floyd-steinberg";
export interface GrayImage { width: number; height: number; pixels: ReadonlyArray<number>; alpha?: ReadonlyArray<number>; }
export interface RasterOptions { dpi: number; intervalMm?: number; mode: RasterDither; threshold?: number; transparent?: "white" | "black"; overscanMm?: number; maxPixels?: number; maxCommands?: number; signal?: AbortSignal; }
export interface RasterPoint { xMm: number; yMm: number; power: number; }
export interface RasterPlan { width: number; height: number; widthMm: number; heightMm: number; intervalMm: number; points: ReadonlyArray<RasterPoint>; rows: ReadonlyArray<ReadonlyArray<RasterPoint>>; }
const finite=(n:number)=>Number.isFinite(n);
function check(o:RasterOptions, image:GrayImage) { if (!Number.isInteger(image.width)||!Number.isInteger(image.height)||image.width<1||image.height<1) throw new Error("Invalid raster dimensions"); if(image.pixels.length!==image.width*image.height) throw new Error("Raster pixel data length mismatch"); if(image.alpha && image.alpha.length!==image.pixels.length) throw new Error("Raster alpha data length mismatch"); if(!finite(o.dpi)||o.dpi<=0) throw new Error("DPI must be positive"); const max=o.maxPixels??16_000_000; if(image.width*image.height>max) throw new Error("Raster pixel limit exceeded"); if(o.mode==="threshold" && o.threshold!==undefined && (!finite(o.threshold)||o.threshold<0||o.threshold>255)) throw new Error("Threshold must be 0..255"); }
export function prepareRaster(image:GrayImage, options:RasterOptions):RasterPlan { check(options,image); const interval=options.intervalMm??(25.4/options.dpi); if(!finite(interval)||interval<=0) throw new Error("Interval must be positive"); const overscan=options.overscanMm??0; if(!finite(overscan)||overscan<0) throw new Error("Overscan must be non-negative"); const values=image.pixels.map((v,i)=>{ let p=Math.max(0,Math.min(255,v)); const a=image.alpha?.[i]??255; if(a<255) p=options.transparent==="black"?p*(a/255):255-(255-p)*(a/255); return p; }); const threshold=options.threshold??128; if(options.mode==="floyd-steinberg"){ for(let y=0;y<image.height;y++) for(let x=0;x<image.width;x++){ if(options.signal?.aborted) throw new DOMException("Raster cancelled","AbortError"); const i=y*image.width+x, old=values[i]??0, next=old>=threshold?255:0, e=old-next; values[i]=next; if(x+1<image.width) values[i+1]=(values[i+1]??0)+e*7/16; if(y+1<image.height){if(x>0)values[i+image.width-1]=(values[i+image.width-1]??0)+e*3/16;values[i+image.width]=(values[i+image.width]??0)+e*5/16;if(x+1<image.width)values[i+image.width+1]=(values[i+image.width+1]??0)+e/16;}} } else if(options.mode==="threshold") values.forEach((v,i)=>values[i]=v>=threshold?255:0);
 const rows:RasterPoint[][]=[]; let count=0; for(let y=0;y<image.height;y++){if(options.signal?.aborted) throw new DOMException("Raster cancelled","AbortError"); const xs=[...Array(image.width).keys()]; if(y%2)xs.reverse(); const row=xs.map(x=>({xMm:x*interval-overscan,yMm:y*interval,power:Math.round(100-(values[y*image.width+x]??255)*100/255)})); rows.push(row); count+=row.length; if(count>(options.maxCommands??32_000_000)) throw new Error("Raster command limit exceeded");} return {width:image.width,height:image.height,widthMm:Math.max(0,(image.width-1)*interval)+overscan*2,heightMm:Math.max(0,(image.height-1)*interval),intervalMm:interval,points:rows.flat(),rows}; }
