import {buildLineCam,generateGrbl,type CamControllerProfile,type CamResult} from "../cam/line-cam.js";
import {parseProject,type ProjectDocument} from "../domain/project.js";
export type SupervisedFillTestId="H-FILL-01"|"H-PASS-01";
export interface SupervisedMachineProfile extends CamControllerProfile{widthMm:number;heightMm:number;}
export interface PreparedSupervisedFill{testId:SupervisedFillTestId;project:ProjectDocument;result:CamResult;code:string;}
export function prepareSupervisedFill(input:ProjectDocument,controller:SupervisedMachineProfile):PreparedSupervisedFill{
 const project=parseProject(input);if(!Number.isFinite(controller.maxPower)||controller.maxPower<=0)throw new Error("Supervised Fill requires valid controller $30.");if(!controller.laserMode)throw new Error("Supervised Fill requires controller $32=1.");if(!Number.isFinite(controller.widthMm)||!Number.isFinite(controller.heightMm)||controller.widthMm<=0||controller.heightMm<=0)throw new Error("Supervised Fill requires a verified live workspace.");
 const enabled=project.operations.filter(operation=>operation.enabled);if(enabled.length!==1||enabled[0]?.kind!=="fill")throw new Error("Supervised testing requires exactly one enabled Fill operation.");const operation=enabled[0];
 if(operation.powerPercent!==15)throw new Error("Supervised Sprint 10 tests require exactly 15% power.");if(operation.speedMmPerMin!==600)throw new Error("Supervised Sprint 10 tests require exactly 600 mm/min.");if(operation.passes!==1&&operation.passes!==2)throw new Error("Supervised Sprint 10 tests allow one or two passes only.");if(operation.lineSpacingMm<0.05||operation.lineSpacingMm>1)throw new Error("Supervised Fill line spacing must be between 0.05 and 1 mm.");
 const result=buildLineCam(project,controller);const width=result.bounds.maxX-result.bounds.minX,height=result.bounds.maxY-result.bounds.minY;if(width<=0||height<=0||width>10||height>10)throw new Error("Supervised Fill bounds must fit within 10 mm × 10 mm.");if(result.bounds.minX<1||result.bounds.minY<1||result.bounds.maxX>controller.widthMm||result.bounds.maxY>controller.heightMm)throw new Error("Supervised Fill exceeds the verified live workspace.");if(result.estimatedSeconds>180||result.paths.length>1_000)throw new Error("Supervised Fill exceeds the duration or path-count limit.");const code=generateGrbl(result);if(code.trim().split(/\r?\n/).length>5_000)throw new Error("Supervised Fill exceeds the G-code line limit.");return{testId:operation.passes===1?"H-FILL-01":"H-PASS-01",project,result,code};
}
