import { useState } from "react";
import type { EditorCommand, EditorHistory } from "../../../editor/editor-state";

export function ArrangeMenu({editor,onCommand,canMoveLaser=false,onMoveLaser,label="Arrange"}:{editor:EditorHistory|null;onCommand:(command:EditorCommand)=>void;canMoveLaser?:boolean;onMoveLaser?:()=>void;label?:string}){
  const count=editor?.present.selectedIds.length??0,[columns,setColumns]=useState(2),[rows,setRows]=useState(2),[spacing,setSpacing]=useState(20),[circleCount,setCircleCount]=useState(6),[angle,setAngle]=useState(0),[scale,setScale]=useState(1);
  const project=editor?.present.project,selected=project?.objects.filter(object=>editor?.present.selectedIds.includes(object.id))??[],hasGroup=selected.some(object=>object.groupId),hasLocked=Boolean(project?.objects.some(object=>object.locked)),hasPath=selected.some(object=>object.type==="path"),hasBreakable=selected.some(object=>object.type==="path"&&object.pointsMm.length>=3),hasOutline=selected.some(object=>!object.locked);
  const run=(command:EditorCommand)=>onCommand(command);
  return <details className="nav-menu arrange-menu"><summary>{label}</summary><div>
    <fieldset><legend>Group</legend><button disabled={count<2} onClick={()=>run({type:"group"})}>Group</button><button disabled={!hasGroup} onClick={()=>run({type:"ungroup"})}>Ungroup</button><button disabled={count<2} onClick={()=>run({type:"auto-group"})}>Automatically group</button></fieldset>
    <fieldset><legend>Align</legend><button disabled={count<2} onClick={()=>run({type:"align",alignment:"left"})}>Align left</button><button disabled={count<2} onClick={()=>run({type:"align",alignment:"center-x"})}>Align horizontal centers</button><button disabled={count<2} onClick={()=>run({type:"align",alignment:"right"})}>Align right</button><button disabled={count<2} onClick={()=>run({type:"align",alignment:"top"})}>Align top</button><button disabled={count<2} onClick={()=>run({type:"align",alignment:"center-y"})}>Align vertical centers</button><button disabled={count<2} onClick={()=>run({type:"align",alignment:"bottom"})}>Align bottom</button></fieldset>
    <fieldset><legend>Distribute</legend><button disabled={count<3} onClick={()=>run({type:"distribute",axis:"x"})}>Distribute horizontally</button><button disabled={count<3} onClick={()=>run({type:"distribute",axis:"y"})}>Distribute vertically</button></fieldset>
    <fieldset><legend>Transform</legend><button disabled={!count} onClick={()=>run({type:"mirror",axis:"x"})}>Mirror horizontally</button><button disabled={!count} onClick={()=>run({type:"mirror",axis:"y"})}>Mirror vertically</button><button disabled={!count} onClick={()=>run({type:"rotate",degrees:90})}>Rotate 90° clockwise</button><button disabled={!count} onClick={()=>run({type:"rotate",degrees:-90})}>Rotate 90° counter-clockwise</button><label>Angle °<input type="number" value={angle} onChange={event=>setAngle(Number(event.target.value))}/></label><label>Scale<input type="number" min="0.01" step="0.1" value={scale} onChange={event=>setScale(Number(event.target.value))}/></label><button disabled={!count||!Number.isFinite(angle)||!Number.isFinite(scale)||scale<=0} onClick={()=>{run({type:"scale",scaleX:scale,scaleY:scale});run({type:"rotate",degrees:angle});}}>Two-point rotate / scale</button></fieldset>
    <fieldset><legend>Arrange copies</legend><div className="arrange-fields"><label>Columns<input type="number" min="1" max="100" value={columns} onChange={event=>setColumns(Number(event.target.value))}/></label><label>Rows<input type="number" min="1" max="100" value={rows} onChange={event=>setRows(Number(event.target.value))}/></label><label>Spacing mm<input type="number" value={spacing} onChange={event=>setSpacing(Number(event.target.value))}/></label></div><button disabled={!count} onClick={()=>run({type:"array",columns,rows,dxMm:spacing,dyMm:spacing})}>Rectangular array</button><label>Circle copies<input type="number" min="2" max="100" value={circleCount} onChange={event=>setCircleCount(Number(event.target.value))}/></label><button disabled={!count} onClick={()=>run({type:"array",mode:"polar",columns:circleCount,rows:1,dxMm:spacing,dyMm:spacing,angleDeg:360/circleCount})}>Circular array</button><button disabled={!hasPath||count<2} onClick={()=>run({type:"array-along-path",copies:circleCount})}>Copy along selected path</button></fieldset>
    <fieldset><legend>Selection</legend><button disabled={!count} onClick={()=>run({type:"select-layer"})}>Select objects on selected layer</button><button disabled={!count} onClick={()=>run({type:"move-selection",target:"origin"})}>Move selection to origin</button><button disabled={!count} onClick={()=>run({type:"move-selection",target:"bed-center"})}>Move selection to bed center</button><button disabled={!hasOutline} onClick={()=>run({type:"outline"})}>Create rubber-band outline</button><button disabled={!hasBreakable} onClick={()=>run({type:"break-apart"})}>Break paths apart</button></fieldset>
    <fieldset><legend>Order and lock</legend><button disabled={!count} onClick={()=>run({type:"reorder",position:"front"})}>Bring to front</button><button disabled={!count} onClick={()=>run({type:"reorder",position:"back"})}>Send to back</button><button disabled={!count} onClick={()=>run({type:"set-object-locked",locked:true})}>Lock selected objects</button><button disabled={!hasLocked} onClick={()=>run({type:"set-object-locked",locked:false})}>Unlock all objects</button></fieldset>
    <fieldset><legend>Laser position</legend><button disabled={!canMoveLaser||!count} onClick={onMoveLaser}>Move laser to selection center</button><small>Laser-off movement; available only while connected and idle.</small></fieldset>
  </div></details>;
}
