import { useMemo, useState } from "react";
import { buildLineCam, generateGrbl } from "../../../cam/line-cam";
import type { ProjectDocument } from "../../../domain/project";
import { getBridge } from "../platform";

export function CamPreviewDialog({project,onClose,onStatus,onSupervise}:{project:ProjectDocument;onClose:()=>void;onStatus:(value:string)=>void;onSupervise?:()=>void}){
  const [maxPower,setMaxPower]=useState(1000);const [laserMode,setLaserMode]=useState(false);
  const outcome=useMemo(()=>{try{const cam=buildLineCam(project,{maxPower,laserMode});return{cam,code:generateGrbl(cam),error:""};}catch(error){return{cam:null,code:"",error:error instanceof Error?error.message:"Preflight failed."};}},[project,maxPower,laserMode]);
  const exportCode=async()=>{if(!outcome.cam)return;const result=await getBridge().exportGcode(outcome.code,project.name);onStatus(result.status==="ok"?`Exported ${result.fileName}`:result.status==="error"?`Export failed: ${result.message}`:"Export cancelled");};
  return <div className="dialog-backdrop" role="presentation"><section className="cam-dialog" role="dialog" aria-modal="true" aria-labelledby="cam-title"><header><div><span className="simulator-dialog__eyebrow">Vector and Fill export</span><h2 id="cam-title">Vector CAM preview</h2></div><button onClick={onClose}>Close</button></header>
    <div className="cam-settings"><label>Controller $30<input type="number" min="1" step="1" value={maxPower} onChange={event=>setMaxPower(Number(event.target.value))}/></label><label className="cam-check"><input type="checkbox" checked={laserMode} onChange={event=>setLaserMode(event.target.checked)}/>I verified controller setting $32=1</label></div>
    {outcome.cam?<><dl className="cam-summary"><div><dt>Paths</dt><dd>{outcome.cam.paths.length}</dd></div><div><dt>Bounds</dt><dd>{outcome.cam.bounds.minX}…{outcome.cam.bounds.maxX} × {outcome.cam.bounds.minY}…{outcome.cam.bounds.maxY} mm</dd></div><div><dt>Estimate</dt><dd>≈ {outcome.cam.estimatedSeconds.toFixed(1)} s</dd></div><div><dt>Max power</dt><dd>{outcome.cam.maxPowerPercent}% / S{Math.round(outcome.cam.maxPowerPercent/100*maxPower)}</dd></div></dl><svg className="cam-preview" viewBox="0 0 400 400" role="img" aria-label="Generated toolpath preview">{outcome.cam.paths.map((path,index)=><polyline key={`${path.objectId}-${path.pass}-${index}`} points={[...path.points,...(path.closed?[path.points[0]!]:[])].map(p=>p.join(",")).join(" ")} fill="none"/>)}</svg><details><summary>Generated G-code ({outcome.code.split("\n").length-1} lines)</summary><pre>{outcome.code}</pre></details><button className="cam-export" onClick={()=>void exportCode()}>Export .gc / .nc</button>{onSupervise&&project.operations.some(operation=>operation.enabled&&operation.kind==="fill")?<button className="gate-c-button" onClick={onSupervise}>Open supervised Fill test</button>:null}</>:<p className="cam-error" role="alert">Preflight blocked: {outcome.error}</p>}
    <p className="simulator-warning">Export only. Generated Fill jobs cannot be sent or started on real hardware from this dialog.</p></section></div>;
}
