import { memo, useEffect, useMemo, useRef, useState, type CSSProperties, type PointerEvent, type WheelEvent } from "react";
import { applyTransform, type ProjectObject } from "../../../domain/project";
import type { EditorCommand, EditorHistory } from "../../../editor/editor-state";
import { Icon } from "./Icon";
import type { DrawingTool } from "./ToolRail";
import { getTranslations, type Translator } from "../i18n";
import "../canvas-interaction-overrides.css";
import { findTrimSegment } from "../../../editor/trim-shapes";

type Point={x:number;y:number};
type CutContact=Point&{objectId:string;pointIndex:number};
type Bounds={minX:number;minY:number;maxX:number;maxY:number};
type Gesture=
  |{kind:"pan";startClient:Point;startScroll:Point}
  |{kind:"move";start:Point;last:Point}
  |{kind:"select-box";start:Point;last:Point;additive:boolean}
  |{kind:"draw";tool:"rectangle"|"rounded-rectangle"|"ellipse"|"line";start:Point;last:Point}
  |{kind:"resize";start:Point;last:Point;bounds:Bounds;handle:"nw"|"n"|"ne"|"e"|"se"|"s"|"sw"|"w";free:boolean}
  |{kind:"rotate";center:Point;startAngle:number;lastAngle:number}
  |{kind:"node";objectId:string;nodeIndex:number;last:Point};

function objectPoints(object:ProjectObject):Array<[number,number]>{if(object.type==="path"){const result:Array<[number,number]>=[];for(const point of object.pointsMm)result.push(applyTransform(object.transform,point));return result;}if(object.type==="ellipse")return Array.from({length:24},(_,index)=>{const angle=index/24*Math.PI*2;return applyTransform(object.transform,[Math.cos(angle)*object.radiusXMm,Math.sin(angle)*object.radiusYMm]);});if(object.type==="text"){const width=Math.max(object.fontSizeMm*.6,object.text.length*object.fontSizeMm*.62),offset=object.alignment==="center"?-width/2:object.alignment==="right"?-width:0;return [[offset,0],[offset+width,0],[offset+width,object.fontSizeMm],[offset,object.fontSizeMm]].map(point=>applyTransform(object.transform,point as [number,number]));}const width=object.widthMm,height=object.heightMm;return [[0,0],[width,0],[width,height],[0,height]].map(point=>applyTransform(object.transform,point as [number,number]));}

function textWidth(object:Extract<ProjectObject,{type:"text"}>):number{return Math.max(object.fontSizeMm*.6,object.text.length*object.fontSizeMm*.62);}
function textCurvePath(object:Extract<ProjectObject,{type:"text"}>):string{const width=textWidth(object),radius=object.curveRadiusMm;if(!radius)return "";return `M 0 ${object.fontSizeMm} A ${radius} ${radius} 0 0 1 ${width} ${object.fontSizeMm}`;}
function boundsOf(objects:ProjectObject[]):Bounds|undefined{const points=objects.flatMap(objectPoints);if(!points.length)return;let minX=Infinity,minY=Infinity,maxX=-Infinity,maxY=-Infinity;for(const[x,y]of points){minX=Math.min(minX,x);minY=Math.min(minY,y);maxX=Math.max(maxX,x);maxY=Math.max(maxY,y);}return{minX,minY,maxX,maxY};}
// eslint-disable-next-line react-refresh/only-export-components
export function objectsInBounds(objects:ProjectObject[],bounds:Bounds){return objects.flatMap(object=>{const candidate=boundsOf([object]);return candidate&&candidate.maxX>=bounds.minX&&candidate.minX<=bounds.maxX&&candidate.maxY>=bounds.minY&&candidate.minY<=bounds.maxY?[object.id]:[];});}
function localPoint(object:ProjectObject,point:Point):[number,number]{const[a,b,c,d,e,f]=object.transform,det=a*d-b*c;if(Math.abs(det)<1e-9)return[point.x,point.y];return[(d*(point.x-e)-c*(point.y-f))/det,(-b*(point.x-e)+a*(point.y-f))/det];}

const ObjectShape=memo(function ObjectShape({object,color,selected,onPointerDown}:{object:ProjectObject;color:string;selected:boolean;onPointerDown:(event:PointerEvent<SVGElement>)=>void}){const[a,b,c,d,e,f]=object.transform,pointerEvents:CSSProperties["pointerEvents"]=object.type==="path"&&!object.closed?"visibleStroke":"all",transform=object.type==="text"?`matrix(${a} ${b} ${c} ${d} ${e} ${f}) translate(0 ${object.fontSizeMm}) scale(1 -1)`:`matrix(${a} ${b} ${c} ${d} ${e} ${f})`,common={className:selected?`canvas-object canvas-object--${object.type} canvas-object--selected`:`canvas-object canvas-object--${object.type}`,onPointerDown,style:{color,pointerEvents},transform};const points=useMemo(()=>object.type==="path"?object.pointsMm.map(([x,y])=>`${x},${y}`).join(" "):"",[object]);if(object.type==="rectangle")return <rect {...common} x={0} y={0} width={object.widthMm} height={object.heightMm} rx={object.cornerRadiusMm} fill="none"/>;if(object.type==="ellipse")return <ellipse {...common} cx={0} cy={0} rx={object.radiusXMm} ry={object.radiusYMm} fill="none"/>;if(object.type==="text")return <text {...common} x={0} y={object.curveRadiusMm?undefined:object.fontSizeMm} fontFamily={object.fontFamily} fontSize={object.fontSizeMm} textAnchor={object.curveRadiusMm?"start":object.alignment==="center"?"middle":object.alignment==="right"?"end":"start"} fill="currentColor" stroke="none">{object.curveRadiusMm?<textPath href={`#text-curve-${object.id}`} startOffset={object.alignment==="center"?"50%":object.alignment==="right"?"100%":"0%"} textAnchor={object.alignment==="center"?"middle":object.alignment==="right"?"end":"start"}>{object.text}</textPath>:object.text}</text>;if(object.type==="raster")return <image {...common} href={`data:${object.mimeType};base64,${object.dataBase64}`} width={object.widthMm} height={object.heightMm} preserveAspectRatio="xMidYMid meet"/>;return <polyline {...common} points={points} fill={object.closed?`${color}24`:"none"}/>;});

const ZOOM_LEVELS=[1/3,.5,.67,.75,1,1.25,1.5,2,3,4,5,7.5,10] as const;
const AXIS_STEPS=[10,20,50,100,200,500,1000] as const;
const LAYER_PALETTE=["#121619","#3155ff","#ff3045","#16c94f","#d3e51b","#f5a000","#00c9c7","#f01bc0","#777b82","#244bb4","#c8192b","#178c32","#a5ae18","#b87805","#1495b2","#a82a9d","#696a6e","#7f8da6","#a86168","#6b55bd","#df6d83","#8cc391","#d39d7c","#d786ad","#7c3fa8","#d58d16","#157f86","#258c75","#78c39c","#e9c764"] as const;
const TOOL_PALETTE=[{label:"T1",color:"#e56d27"},{label:"T2",color:"#148ec2"}] as const;
// eslint-disable-next-line react-refresh/only-export-components
export function clampZoom(value:number){return Math.min(10,Math.max(1/3,value));}
// eslint-disable-next-line react-refresh/only-export-components
export function axisTicks(max:number,pixelsPerMm:number){const step=AXIS_STEPS.find(candidate=>candidate*pixelsPerMm>=30)??AXIS_STEPS.at(-1)??1000,values=Array.from({length:Math.floor(max/step)+1},(_,index)=>index*step);if(values.at(-1)!==max)values.push(max);return values;}
function paletteForeground(color:string){const red=parseInt(color.slice(1,3),16),green=parseInt(color.slice(3,5),16),blue=parseInt(color.slice(5,7),16);return red*.299+green*.587+blue*.114>145?"#101519":"#f7fbfd";}

export function CanvasStage({editor,onAction,onCommand,activeTool="select",machineHome,t}:{editor:EditorHistory|null;onAction:(action:"new"|"open")=>void;onCommand:(command:EditorCommand)=>void;activeTool?:DrawingTool;machineHome?:{connected:boolean;xMm:number;yMm:number};t?:Translator}){
  const[zoom,setZoom]=useState(1),[gesture,setGesture]=useState<Gesture>(),[polygon,setPolygon]=useState<Point[]>([]),[cutPoints,setCutPoints]=useState<CutContact[]>([]),[fitSize,setFitSize]=useState({width:400,height:400});const svgRef=useRef<SVGSVGElement>(null),scrollRef=useRef<HTMLElement>(null);
  const [trimTarget, setTrimTarget] = useState<ReturnType<typeof findTrimSegment>>();
  const project=editor?.present.project??null,selectedIds=editor?.present.selectedIds??[],selected=new Set(selectedIds),width=project?.machine.widthMm??400,height=project?.machine.heightMm??400,labels=t??getTranslations("en");
  const visibleLayers=useMemo(()=>new Set(project?.layers.filter(({visible})=>visible).map(({id})=>id)),[project?.layers]);const lockedLayers=useMemo(()=>new Set(project?.layers.filter(({locked})=>locked).map(({id})=>id)),[project?.layers]);const layerColors=useMemo(()=>new Map(project?.layers.map((layer,index)=>[layer.id,layer.color??["#68c5e8","#f45ac6","#7ddc78","#f4c45e","#a68cff"][index%5]])),[project?.layers]);
  const selectedObjects=project?.objects.filter(object=>selected.has(object.id))??[];const selectionBounds=boundsOf(selectedObjects),selectedLayerIds=new Set(selectedObjects.map(object=>object.layerId));
  const paletteLayer=project?(selectedLayerIds.size>1?undefined:project.layers.find(layer=>layer.id===selectedObjects[0]?.layerId)??project.layers.find(layer=>layer.visible&&!layer.locked)??project.layers[0]):undefined,paletteColor=paletteLayer?(paletteLayer.color??layerColors.get(paletteLayer.id)??"").toLowerCase():"";
  const toPoint=(clientX:number,clientY:number):Point=>{const rect=svgRef.current?.getBoundingClientRect();if(!rect||rect.width<=0||rect.height<=0)return{x:0,y:0};return{x:(clientX-rect.left)/rect.width*width,y:height-(clientY-rect.top)/rect.height*height};};
  const beginPan=(event:PointerEvent<SVGElement>)=>{event.preventDefault();event.stopPropagation();svgRef.current?.setPointerCapture?.(event.pointerId);const container=scrollRef.current;setGesture({kind:"pan",startClient:{x:event.clientX,y:event.clientY},startScroll:{x:container?.scrollLeft??0,y:container?.scrollTop??0}});};
const beginCanvas=(event:PointerEvent<SVGSVGElement>)=>{if(event.button===2){beginPan(event);return;}if(!project)return;const point=toPoint(event.clientX,event.clientY);if(activeTool==="cut"){const candidate=findTrimSegment(project,[point.x,point.y],visibleLayers,lockedLayers,Math.max(4,12/zoom));if(!candidate)return;onCommand({type:"trim-path",objectId:candidate.objectId,segmentIndex:candidate.segmentIndex});setTrimTarget(undefined);return;}if(activeTool==="select"){event.currentTarget.setPointerCapture?.(event.pointerId);setGesture({kind:"select-box",start:point,last:point,additive:event.ctrlKey||event.metaKey||event.shiftKey});return;}if(activeTool==="rectangle"||activeTool==="rounded-rectangle"||activeTool==="ellipse"||activeTool==="line"){event.currentTarget.setPointerCapture?.(event.pointerId);setGesture({kind:"draw",tool:activeTool,start:point,last:point});return;}if(activeTool==="polygon"){setPolygon(current=>[...current,point]);return;}if(activeTool==="text"){onCommand({type:"add-text",xMm:point.x,yMm:point.y,text:"Text",heightMm:10});return;}if(activeTool==="array")onCommand({type:"array",columns:2,rows:2,dxMm:10,dyMm:10});};
  const movePointer=(event:PointerEvent<SVGSVGElement>)=>{const point=toPoint(event.clientX,event.clientY);if(activeTool==="cut"&&!gesture){setTrimTarget(project?findTrimSegment(project,[point.x,point.y],visibleLayers,lockedLayers,Math.max(4,12/zoom)):undefined);return;}if(!gesture)return;if(gesture.kind==="pan"){const container=scrollRef.current;if(container){container.scrollLeft=gesture.startScroll.x-(event.clientX-gesture.startClient.x);container.scrollTop=gesture.startScroll.y-(event.clientY-gesture.startClient.y);}return;}setGesture(current=>current?(current.kind==="rotate"?{...current,lastAngle:Math.atan2(point.y-current.center.y,point.x-current.center.x)}:current.kind==="resize"?{...current,last:point,free:event.shiftKey}:{...current,last:point}):current);};
  const endPointer=()=>{if(!gesture||!project)return;const current=gesture;setGesture(undefined);if(current.kind==="pan")return;if(current.kind==="move"){const dx=current.last.x-current.start.x,dy=current.last.y-current.start.y;if(Math.hypot(dx,dy)>.01)onCommand({type:"translate",dxMm:dx,dyMm:dy});}else if(current.kind==="select-box"){const bounds={minX:Math.min(current.start.x,current.last.x),minY:Math.min(current.start.y,current.last.y),maxX:Math.max(current.start.x,current.last.x),maxY:Math.max(current.start.y,current.last.y)};if(Math.hypot(bounds.maxX-bounds.minX,bounds.maxY-bounds.minY)<.5)onCommand({type:"clear-selection"});else onCommand({type:"select-many",ids:objectsInBounds(project.objects.filter(object=>visibleLayers.has(object.layerId)&&!lockedLayers.has(object.layerId)),bounds),additive:current.additive});}else if(current.kind==="draw"){const minX=Math.min(current.start.x,current.last.x),minY=Math.min(current.start.y,current.last.y),dx=Math.abs(current.last.x-current.start.x),dy=Math.abs(current.last.y-current.start.y);if(dx<.1&&dy<.1)return;if(current.tool==="rectangle"||current.tool==="rounded-rectangle")onCommand({type:"add-rectangle",xMm:minX,yMm:minY,widthMm:dx,heightMm:dy,cornerRadiusMm:current.tool==="rounded-rectangle"?Math.min(5,dx/2,dy/2):0});else if(current.tool==="ellipse")onCommand({type:"add-ellipse",xMm:(current.start.x+current.last.x)/2,yMm:(current.start.y+current.last.y)/2,radiusXMm:dx/2,radiusYMm:dy/2});else onCommand({type:"add-line",xMm:current.start.x,yMm:current.start.y,lengthMm:Math.max(.1,Math.hypot(dx,dy)),endXmm:current.last.x,endYmm:current.last.y});}else if(current.kind==="resize"){const baseW=Math.max(.001,current.bounds.maxX-current.bounds.minX),baseH=Math.max(.001,current.bounds.maxY-current.bounds.minY),east=current.handle.includes("e"),west=current.handle.includes("w"),north=current.handle.includes("n"),south=current.handle.includes("s");let sx=east?1+(current.last.x-current.start.x)/baseW:west?1-(current.last.x-current.start.x)/baseW:1,sy=north?1+(current.last.y-current.start.y)/baseH:south?1-(current.last.y-current.start.y)/baseH:1;if(!current.free&&(east||west)&&(north||south)){const scale=Math.max(.02,Math.abs(sx-1)>Math.abs(sy-1)?sx:sy);sx=scale;sy=scale;}onCommand({type:"scale",scaleX:Math.max(.02,sx),scaleY:Math.max(.02,sy)});}else if(current.kind==="rotate")onCommand({type:"rotate",degrees:(current.lastAngle-current.startAngle)*180/Math.PI});else if(current.kind==="node"){const object=project.objects.find(item=>item.id===current.objectId);if(object)onCommand({type:"move-node",objectId:current.objectId,nodeIndex:current.nodeIndex,pointMm:localPoint(object,current.last)});}};
  const wheelZoom=(event:WheelEvent)=>{if(!project)return;event.preventDefault();const container=scrollRef.current;if(!container)return;const old=zoom,next=clampZoom(old*Math.exp(-event.deltaY*.0015));if(Math.abs(next-old)<.001)return;const rect=container.getBoundingClientRect(),x=event.clientX-rect.left+container.scrollLeft,y=event.clientY-rect.top+container.scrollTop;setZoom(next);requestAnimationFrame(()=>{container.scrollLeft=x*next/old-(event.clientX-rect.left);container.scrollTop=y*next/old-(event.clientY-rect.top);});};
  const finishPolygon=()=>{if(polygon.length>=3)onCommand({type:"add-polygon",pointsMm:polygon.map(({x,y})=>[x,y])});setPolygon([]);};
  useEffect(()=>{if(activeTool!=="polygon"&&activeTool!=="cut")return;const key=(event:KeyboardEvent)=>{if(event.key==="Enter"&&activeTool==="polygon"){event.preventDefault();if(polygon.length>=3)onCommand({type:"add-polygon",pointsMm:polygon.map(({x,y})=>[x,y])});setPolygon([]);}else if(event.key==="Escape"){setPolygon([]);setCutPoints([]);}};window.addEventListener("keydown",key);return()=>window.removeEventListener("keydown",key);},[activeTool,onCommand,polygon]);
  useEffect(()=>{const container=scrollRef.current;if(!container)return;const update=()=>{const style=getComputedStyle(container),horizontalPadding=parseFloat(style.paddingLeft||"0")+parseFloat(style.paddingRight||"0"),verticalPadding=parseFloat(style.paddingTop||"0")+parseFloat(style.paddingBottom||"0"),availableWidth=Math.max(80,container.clientWidth-horizontalPadding),availableHeight=Math.max(80,container.clientHeight-verticalPadding),scale=Math.min(availableWidth/width,availableHeight/height);setFitSize({width:width*scale,height:height*scale});};update();if(typeof ResizeObserver==="undefined")return;const observer=new ResizeObserver(update);observer.observe(container);return()=>observer.disconnect();},[width,height]);
  const preview=gesture&&("start"in gesture)?{x:Math.min(gesture.start.x,gesture.last.x),y:Math.min(gesture.start.y,gesture.last.y),w:Math.abs(gesture.last.x-gesture.start.x),h:Math.abs(gesture.last.y-gesture.start.y)}:undefined;
  const surfaceStyle={"--canvas-zoom":zoom,aspectRatio:`${width} / ${height}`,width:fitSize.width*zoom,height:fitSize.height*zoom} as CSSProperties;
  const handleRadius=3/zoom,homeX=Math.min(width,Math.max(0,machineHome?.xMm??0)),homeY=Math.min(height,Math.max(0,machineHome?.yMm??0));
  const xTicks=axisTicks(width,fitSize.width/width*zoom),yTicks=axisTicks(height,fitSize.height/height*zoom);
  const resizeHandles=selectionBounds?([['nw',selectionBounds.minX,selectionBounds.maxY],['n',(selectionBounds.minX+selectionBounds.maxX)/2,selectionBounds.maxY],['ne',selectionBounds.maxX,selectionBounds.maxY],['e',selectionBounds.maxX,(selectionBounds.minY+selectionBounds.maxY)/2],['se',selectionBounds.maxX,selectionBounds.minY],['s',(selectionBounds.minX+selectionBounds.maxX)/2,selectionBounds.minY],['sw',selectionBounds.minX,selectionBounds.minY],['w',selectionBounds.minX,(selectionBounds.minY+selectionBounds.maxY)/2]] as const):[];
  return <main className="canvas-stage" aria-label={labels.editorActions}><div className="ruler ruler--horizontal" aria-hidden="true"/><div className="ruler ruler--vertical" aria-hidden="true"/><section ref={scrollRef} className="work-area" aria-label={`${labels.workArea} ${width} by ${height} millimetres`} data-zoom={`${Math.round(zoom*100)}%`} onWheel={wheelZoom}><div className="document-surface" style={surfaceStyle}>
    <div className="axis-scale axis-scale--x" aria-label="X axis millimetres">{xTicks.map((value,index)=><span key={value} aria-label={`X ${value} mm`} data-edge={index===0?"start":index===xTicks.length-1?"end":undefined} style={{left:`${value/width*100}%`}}>{value}</span>)}</div>
    <div className="axis-scale axis-scale--y" aria-label="Y axis millimetres">{yTicks.map((value,index)=><span key={value} aria-label={`Y ${value} mm`} data-edge={index===0?"start":index===yTicks.length-1?"end":undefined} style={{top:`${100-value/height*100}%`}}>{value}</span>)}</div>
    <div className="coordinate-overlay" aria-label="Document coordinates"><span className="origin-marker" aria-label="Origin X 0 Y 0" data-x-mm="0" data-y-mm="0"/><span className="axis-label axis-label--x">+X</span><span className="axis-label axis-label--y">+Y</span><span className="home-marker" aria-label={`Software home X ${homeX.toFixed(1)} Y ${homeY.toFixed(1)}`} data-connected={machineHome?.connected??false} data-x-mm={homeX} data-y-mm={homeY} style={{left:`${homeX/width*100}%`,top:`${100-homeY/height*100}%`}}/></div>
    {project?<svg ref={svgRef} className="document-canvas" viewBox={`0 0 ${width} ${height}`} preserveAspectRatio="xMidYMid meet" role="img" aria-label={`${project.objects.length} document objects`} onContextMenu={event=>event.preventDefault()} onPointerDown={beginCanvas} onPointerMove={movePointer} onPointerUp={endPointer} onPointerCancel={()=>setGesture(undefined)} onDoubleClick={activeTool==="polygon"?finishPolygon:undefined}>
      <defs>{project.objects.filter((object):object is Extract<ProjectObject,{type:"text"}>=>object.type==="text"&&!!object.curveRadiusMm).map(object=><path key={object.id} id={`text-curve-${object.id}`} d={textCurvePath(object)}/>)}</defs>
      <g transform={`translate(0 ${height}) scale(1 -1)`}>
      {project.objects.filter(object=>visibleLayers.has(object.layerId)).map(object=>{const isSelected=selected.has(object.id);return <ObjectShape key={object.id} object={object} color={layerColors.get(object.layerId)??"#68c5e8"} selected={isSelected} onPointerDown={event=>{if(event.button===2){beginPan(event);return;}if(activeTool!=="select"||lockedLayers.has(object.layerId))return;event.stopPropagation();const additive=event.ctrlKey||event.metaKey||event.shiftKey;if(!isSelected||additive)onCommand({type:"select",id:object.id,additive});const point=toPoint(event.clientX,event.clientY);setGesture({kind:"move",start:point,last:point});}}/>;})}
      {activeTool==="cut"&&trimTarget?<line className="trim-preview" x1={trimTarget.a[0]} y1={trimTarget.a[1]} x2={trimTarget.b[0]} y2={trimTarget.b[1]}/>:null}
 {selectionBounds?<g className="selection-overlay"><rect x={selectionBounds.minX} y={selectionBounds.minY} width={selectionBounds.maxX-selectionBounds.minX} height={selectionBounds.maxY-selectionBounds.minY}/>{resizeHandles.map(([handle,x,y])=><circle key={handle} data-handle={handle} className="resize-handle" cx={x} cy={y} r={handleRadius} onPointerDown={event=>{event.stopPropagation();const point=toPoint(event.clientX,event.clientY);setGesture({kind:"resize",start:point,last:point,bounds:selectionBounds,handle,free:event.shiftKey});}}/>)}<circle className="rotate-handle" cx={(selectionBounds.minX+selectionBounds.maxX)/2} cy={selectionBounds.maxY+10/zoom} r={handleRadius} onPointerDown={event=>{event.stopPropagation();const point=toPoint(event.clientX,event.clientY),center={x:(selectionBounds.minX+selectionBounds.maxX)/2,y:(selectionBounds.minY+selectionBounds.maxY)/2},angle=Math.atan2(point.y-center.y,point.x-center.x);setGesture({kind:"rotate",center,startAngle:angle,lastAngle:angle});}}/></g>:null}
      {activeTool==="nodes"?selectedObjects.filter(object=>object.type==="path").flatMap(object=>object.type==="path"?object.pointsMm.map((point,index)=>{const[x,y]=applyTransform(object.transform,point);return <circle key={`${object.id}-${index}`} className="node-handle" cx={x} cy={y} r={handleRadius} onPointerDown={event=>{event.stopPropagation();setGesture({kind:"node",objectId:object.id,nodeIndex:index,last:toPoint(event.clientX,event.clientY)});}}/>;}):[]):null}
       {preview?<rect className="gesture-preview" x={preview.x} y={preview.y} width={preview.w} height={preview.h}/>:null}{polygon.length?<polyline className="gesture-preview" points={polygon.map(({x,y})=>`${x},${y}`).join(" ")}/>:null}{cutPoints.map((point,index)=><circle key={`cut-contact-${index}`} className="node-handle" cx={point.x} cy={point.y} r={handleRadius*1.5}/>)}
      </g>
    </svg>:null}
    {!project?.objects.length?<div className="empty-state"><Icon name="document" size={52}/><h1>{project?project.name:labels.noProjectOpen}</h1><p>{project?`${labels.emptyProject} · ${project.layers.length} ${labels.layer} · ${project.units}`:labels.createOrOpen}</p>{!project?<div className="empty-state__actions"><button type="button" onClick={()=>onAction("new")}><Icon name="document"/>{labels.newProject}</button><button type="button" onClick={()=>onAction("open")}><Icon name="open"/>{labels.openProject}</button></div>:null}</div>:null}
  </div></section><div className="canvas-toolbar" aria-label="Editor actions"><label className="zoom-control">Zoom<select aria-label="Canvas zoom" value={zoom} onChange={event=>setZoom(clampZoom(Number(event.target.value)))}>{ZOOM_LEVELS.map(level=><option key={level} value={level}>{Math.round(level*100)}%</option>)}</select></label><span>{selected.size} selected</span><button disabled={!selected.size} onClick={()=>onCommand({type:"delete"})}>Delete</button><button disabled={!selected.size} onClick={()=>onCommand({type:"copy"})}>Copy</button><button disabled={!editor?.clipboard.length} onClick={()=>onCommand({type:"paste"})}>Paste</button><button disabled={!selected.size} onClick={()=>onCommand({type:"duplicate"})}>Duplicate</button>{activeTool==="polygon"&&polygon.length?<button onClick={finishPolygon}>Finish polygon</button>:null}{activeTool==="nodes"&&selectedObjects.some(object=>object.type==="path")?<><button onClick={()=>{const path=selectedObjects.find(object=>object.type==="path");if(path)onCommand({type:"add-node",objectId:path.id,segmentIndex:0});}}>Add node</button><button onClick={()=>{const path=selectedObjects.find(object=>object.type==="path");if(path)onCommand({type:"delete-node",objectId:path.id,nodeIndex:path.pointsMm.length-1});}}>Delete node</button></>:null}{activeTool==="nodes"&&selectedObjects.some(object=>object.type==="path"&&!object.closed&&object.pointsMm.length>=3)?<button onClick={()=>{const path=selectedObjects.find(object=>object.type==="path"&&!object.closed&&object.pointsMm.length>=3);if(path)onCommand({type:"split-path",objectId:path.id});}}>Split path</button>:null}{activeTool==="array"&&selected.size?<button onClick={()=>onCommand({type:"array",mode:"polar",columns:4,rows:1,dxMm:20,dyMm:20,angleDeg:90})}>Polar array</button>:null}</div><div className="layer-palette" aria-label="Layer colors">{LAYER_PALETTE.map((color,index)=>{const label=String(index).padStart(2,"0");return <button key={color} type="button" aria-label={`Layer color ${label} ${color}`} aria-pressed={paletteColor===color} disabled={!paletteLayer} style={{backgroundColor:color,color:paletteForeground(color)}} onClick={()=>{if(paletteLayer)onCommand({type:"set-layer-color",layerId:paletteLayer.id,color});}}>{label}</button>;})}{TOOL_PALETTE.map(({label,color})=><button key={label} type="button" aria-label={`Tool color ${label} ${color}`} aria-pressed={paletteColor===color} disabled={!paletteLayer} style={{backgroundColor:color,color:paletteForeground(color)}} onClick={()=>{if(paletteLayer)onCommand({type:"set-layer-color",layerId:paletteLayer.id,color});}}>{label}</button>)}</div></main>;
}
