import {useEffect,useRef,useState} from "react";
import type {FirstMarkSummary,GateCApproval,LocalDeviceProfile,MotionSafetyAcknowledgement} from "../../../shared/contracts";
import type {MachineSnapshot} from "../../../machine/machine-controller";
import {getBridge} from "../platform";

const disconnected:MachineSnapshot={connected:false,state:"Unknown",transcript:[]};
const empty:GateCApproval={testId:"H-LASER-02",phrase:"",physicallyPresent:false,workAreaClear:false,emergencyStopReady:false,otherControllersClosed:false,focused:false,materialConfirmed:false,ventilationOn:false,airAssistOn:false,targetFrameConfirmed:false};
export function FirstMarkDialog({onClose}:{onClose:()=>void}){
 const [profile,setProfile]=useState<LocalDeviceProfile>({host:"192.168.178.71",tcpPort:23,cameraPath:"/images/snapshot0.jpg"});const [approval,setApproval]=useState(empty);const [machine,setMachine]=useState(disconnected);const [framed,setFramed]=useState(false);const [summary,setSummary]=useState<FirstMarkSummary>();const [detail,setDetail]=useState("No connection. No emission is possible.");const [camera,setCamera]=useState<{data?:string;last?:number;error?:string}>({});const [clock,setClock]=useState(0);const [starting,setStarting]=useState(false);const [preparing,setPreparing]=useState(false);const [attempted,setAttempted]=useState(false);const [startState,setStartState]=useState<"READY"|"COMMAND SENT"|"COMPLETED"|"FAILED">("READY");const [connecting,setConnecting]=useState(false);const connectInFlight=useRef(false);const prepareInFlight=useRef(false);
 useEffect(()=>{void getBridge().getDeviceProfile().then(setProfile);return()=>{void getBridge().disconnectMachine();};},[]);
 useEffect(()=>{let active=true;const poll=async()=>{const framePromise=getBridge().getCameraFrame({host:profile.host});const snapshotPromise=machine.connected?getBridge().getMachineSnapshot():Promise.resolve(undefined);const [snapshot,frame]=await Promise.all([snapshotPromise,framePromise]);if(!active)return;setClock(Date.now());if(snapshot)setMachine(snapshot);if(frame.status==="ok")setCamera({data:frame.dataUrl,last:Date.now()});else setCamera(current=>({...current,error:frame.message}));};void poll();const timer=window.setInterval(()=>void poll(),1000);return()=>{active=false;window.clearInterval(timer);};},[machine.connected,profile.host]);
 const set=(key:keyof GateCApproval,value:boolean|string)=>setApproval(current=>({...current,[key]:value}));const safetyReady=[approval.physicallyPresent,approval.workAreaClear,approval.emergencyStopReady,approval.otherControllersClosed,approval.focused,approval.materialConfirmed,approval.ventilationOn,approval.airAssistOn].every(Boolean);
 const startBlockReason=attempted?"Start already attempted; close and repeat the full preflight.":starting?"Command is currently running.":approval.phrase!=="H-LASER-02 STARTEN"?"Type the exact confirmation phrase.":machine.state!=="Idle"?`Machine must be Idle; current state is ${machine.state}.`:undefined;
 const connect=async()=>{if(connectInFlight.current)return;connectInFlight.current=true;setConnecting(true);setDetail("Connecting to the supervised machine session…");try{const gate:MotionSafetyAcknowledgement={physicallyPresent:approval.physicallyPresent,workAreaClear:approval.workAreaClear,emergencyStopReady:approval.emergencyStopReady,otherControllersClosed:approval.otherControllersClosed,motionApproved:true,laserOffConfirmed:true};const snapshot=await getBridge().connectMachine({kind:"tcp",host:profile.host,port:profile.tcpPort},gate);setMachine(snapshot);setDetail(`Connected · ${snapshot.state}. Run the laserless target frame next.`);}catch(error){setMachine(await getBridge().getMachineSnapshot());setDetail(error instanceof Error?error.message:"Connection failed.");}finally{connectInFlight.current=false;setConnecting(false);}};
 const prepare=async()=>{if(prepareInFlight.current)return;prepareInFlight.current=true;setPreparing(true);setDetail("Reading the controller settings and preparing the immutable preflight…");try{const next=await getBridge().prepareFirstMark();setSummary(next);setDetail("Preflight prepared. Inspect the summary and type the exact phrase.");}catch(error){setDetail(error instanceof Error?error.message:"Preflight failed.");}finally{prepareInFlight.current=false;setPreparing(false);}};
 const frame=async()=>{try{set("targetFrameConfirmed",false);setDetail("Laserless target framing in progress. Confirm it stays entirely on the wood.");const snapshot=await getBridge().frameFirstMark();setMachine(snapshot);setFramed(true);setDetail("Laserless 10 × 10 mm target frame completed. Confirm below only if it was entirely on the wood.");}catch(error){setFramed(false);set("targetFrameConfirmed",false);setDetail(error instanceof Error?error.message:"Target framing failed.");}};
 const start=async()=>{if(attempted)return;setAttempted(true);setStarting(true);setStartState("COMMAND SENT");setDetail("H-LASER-02 command sent; after M5/S0 the head will automatically home with $H.");try{const snapshot=await getBridge().startFirstMark(approval);setMachine(snapshot);setStartState("COMPLETED");setDetail("H-LASER-02 and final homing completed. The one-shot start is locked; inspect the 10 mm mark.");}catch(error){setStartState("FAILED");setDetail(`H-LASER-02 or final homing did not complete: ${error instanceof Error?error.message:"Calibration mark failed."} Use the physical stop if motion is unsafe, then close this dialog and inspect the machine.`);setMachine(await getBridge().getMachineSnapshot());}finally{setStarting(false);}};
 const stop=async()=>{try{setMachine(await getBridge().machineAction({type:"abort"}));setDetail("Software Stop sent. Inspect, reconnect and re-home.");}catch(error){setDetail(error instanceof Error?error.message:"Stop failed; use the physical emergency stop if danger exists.");}};
 return <div className="dialog-backdrop" role="presentation"><section className="first-mark-dialog" role="dialog" aria-modal="true" aria-labelledby="first-mark-title"><header><div><span className="simulator-dialog__eyebrow">Gate C · user-start only</span><h2 id="first-mark-title">H-LASER-02 · supervised 20 % calibration mark</h2></div><button disabled={starting||connecting} onClick={onClose}>Close</button></header><p role="status">{detail}</p><p aria-label="Machine connection state"><strong>Machine:</strong> {connecting?"Connecting":machine.connected?`Connected · ${machine.state}`:"Disconnected"}</p>
 <div className="first-mark-layout"><section><fieldset className="gate-checks"><legend>Physical confirmation</legend>{([['physicallyPresent','I remain physically at the laser.'],['workAreaClear','The complete motion area is clear.'],['emergencyStopReady','Physical emergency stop is reachable.'],['otherControllersClosed','No other GRBL controller is open.'],['focused','Focus gauge was used on this wood.'],['materialConfirmed','Wood is untreated and secured.'],['ventilationOn','Extraction is running.'],['airAssistOn','Air Assist is running.']] as const).map(([key,label])=><label key={key}><input type="checkbox" checked={approval[key]} onChange={event=>set(key,event.target.checked)}/>{label}</label>)}{framed?<label><input type="checkbox" checked={approval.targetFrameConfirmed} onChange={event=>set("targetFrameConfirmed",event.target.checked)}/>The laserless target frame stayed entirely on the wood.</label>:null}</fieldset><div className="simulator-actions"><button disabled={connecting||machine.connected||!safetyReady} onClick={()=>void connect()}>Connect supervised TCP</button><button disabled={connecting||preparing||!machine.connected||machine.state!=="Idle"||framed} onClick={()=>void frame()}>Frame target without laser</button><button disabled={connecting||preparing||!framed||!approval.targetFrameConfirmed||machine.state!=="Idle"||Boolean(summary)} onClick={()=>void prepare()}>{preparing?"Preparing fixed test…":"Prepare fixed test"}</button></div></section>
 <section className="first-mark-camera">{camera.data?<img src={camera.data} alt="LaserCam supervised live view"/>:<div>No camera frame</div>}<strong>{camera.error?`Camera warning: ${camera.error}`:camera.last?`Camera age ${Math.max(0,clock-camera.last)} ms`:"Camera offline"}</strong><p>Camera failure does not alter GRBL state. Remain at the physical machine.</p></section></div>
 {summary?<section className="first-mark-summary"><h3>Immutable preflight</h3><dl><div><dt>Path</dt><dd>X30,Y35 → X40,Y35</dd></div><div><dt>Length</dt><dd>10 mm</dd></div><div><dt>Speed</dt><dd>{summary.speedMmPerMin} mm/min</dd></div><div><dt>Power</dt><dd>20 % · S200 / $30={summary.maxPower}</dd></div></dl><code>SHA-256 {summary.hash}</code><p aria-label="H-LASER-02 start state"><strong>Start state:</strong> {startState}</p><label>Type exactly: H-LASER-02 STARTEN<input value={approval.phrase} disabled={attempted} onChange={event=>set('phrase',event.target.value)}/></label><button className="first-mark-start" disabled={Boolean(startBlockReason)} onClick={()=>void start()}>{attempted?"H-LASER-02 start locked":"Start H-LASER-02 now"}</button><p aria-label="H-LASER-02 start availability">{startBlockReason??"Start enabled: the next click will send the one-shot command."}</p></section>:null}
 <div className="camera-safety-actions"><button disabled={machine.job?.state!=="running"&&!new Set(["Run","Jog"]).has(machine.state)} onClick={()=>void getBridge().machineAction({type:"hold"}).then(setMachine)}>Hold</button><button disabled={machine.job?.state!=="held"||machine.state!=="Hold"} onClick={()=>void getBridge().machineAction({type:"resume"}).then(setMachine)}>Resume</button><button className="stop-button" disabled={!new Set(["running","held"]).has(machine.job?.state??"")&&!new Set(["Run","Jog","Hold"]).has(machine.state)} onClick={()=>void stop()}>Stop job</button></div>{machine.job?<progress max={machine.job.totalLines} value={machine.job.confirmedLines} aria-label="Confirmed job lines"/>:null}<p className="simulator-warning">This is laser emission. Keep eyes, hands and flammable objects away. Software Stop is not an emergency stop.</p></section></div>;
}
