import { useState } from "react";
import type { MachineAction, MachineSnapshot } from "../../../machine/machine-controller";
import type { JogDirection } from "../../../machine/motion-safety";

type Position={x:number;y:number};
type SavedPositions={start?:Position;end?:Position};

function loadSavedPositions():SavedPositions{try{const value=JSON.parse(localStorage.getItem("atomburn-saved-positions")??"") as SavedPositions;const valid=(position?:Position)=>position&&[position.x,position.y].every(number=>Number.isFinite(number)&&number>=0&&number<=400);return{start:valid(value.start)?value.start:undefined,end:valid(value.end)?value.end:undefined};}catch{return{};}}
function describe(position?:Position){return position?`X ${position.x.toFixed(2)} · Y ${position.y.toFixed(2)}`:"Not set";}

export function MotionWorkspace({machine,machineHome,onSetMachineHome,onOpenMachine,onMachineAction}:{machine?:MachineSnapshot;machineHome?:{xMm:number;yMm:number};onSetMachineHome?:(home:{xMm:number;yMm:number})=>void;onOpenMachine?:()=>void;onMachineAction?:(action:MachineAction)=>void}){
  const[distance,setDistance]=useState(1),[feed,setFeed]=useState(1000),[target,setTarget]=useState<Position>({x:machine?.position?.x??0,y:machine?.position?.y??0}),[saved,setSaved]=useState<SavedPositions>(loadSavedPositions);
  const canMove=Boolean(machine?.connected&&machine.state==="Idle"&&machine.position),validTarget=[target.x,target.y].every(value=>Number.isFinite(value)&&value>=0&&value<=400),validJog=Number.isFinite(distance)&&distance>0&&distance<=10&&Number.isFinite(feed)&&feed>0&&feed<=3000;
  const action=(request:MachineAction)=>onMachineAction?.(request);
  const jog=(direction:JogDirection)=>action({type:"jog",direction,distance,feed});
  const save=(slot:keyof SavedPositions)=>{if(!machine?.position)return;const next={...saved,[slot]:{...machine.position}};setSaved(next);localStorage.setItem("atomburn-saved-positions",JSON.stringify(next));};
  const go=(position?:Position)=>{if(position)action({type:"move-to",x:position.x,y:position.y,feed});};
  return <section className="motion-workspace" aria-label="Machine movement and home">
    <header><span className={`connection-dot connection-dot--${machine?.connected?"online":"offline"}`}/><div><strong>{machine?.connected?"Laser connected":"Laser offline"}</strong><small>GRBL {machine?.state??"Unknown"}</small></div><button type="button" onClick={onOpenMachine}>Connection</button></header>
    <div className="position-readout"><button type="button" aria-label="Refresh machine position" disabled={!machine?.connected} onClick={()=>action({type:"refresh"})}>Refresh position</button><output>X {machine?.position?.x.toFixed(2)??"—"}</output><output>Y {machine?.position?.y.toFixed(2)??"—"}</output><output>Z not supported</output></div>
    <fieldset className="target-position"><legend>Go to XY position</legend><label>X mm<input aria-label="Target X mm" type="number" min="0" max="400" step="0.1" value={target.x} onChange={event=>setTarget(current=>({...current,x:Number(event.target.value)}))}/></label><label>Y mm<input aria-label="Target Y mm" type="number" min="0" max="400" step="0.1" value={target.y} onChange={event=>setTarget(current=>({...current,y:Number(event.target.value)}))}/></label><button type="button" aria-label="Go to target position" disabled={!canMove||!validTarget||!validJog} onClick={()=>go(target)}>Go</button></fieldset>
    <div className="motion-controls"><div className="workspace-jog" aria-label="Jog controls"><button aria-label="Jog upper left" disabled={!canMove||!validJog} onClick={()=>jog("x-y+")}>↖</button><button aria-label="Jog up" disabled={!canMove||!validJog} onClick={()=>jog("y+")}>↑</button><button aria-label="Jog upper right" disabled={!canMove||!validJog} onClick={()=>jog("x+y+")}>↗</button><button aria-label="Jog left" disabled={!canMove||!validJog} onClick={()=>jog("x-")}>←</button><button aria-label="Home machine" disabled={!machine?.connected||!new Set(["Idle","Alarm"]).has(machine.state)} onClick={()=>action({type:"home"})}>⌂</button><button aria-label="Jog right" disabled={!canMove||!validJog} onClick={()=>jog("x+")}>→</button><button aria-label="Jog lower left" disabled={!canMove||!validJog} onClick={()=>jog("x-y-")}>↙</button><button aria-label="Jog down" disabled={!canMove||!validJog} onClick={()=>jog("y-")}>↓</button><button aria-label="Jog lower right" disabled={!canMove||!validJog} onClick={()=>jog("x+y-")}>↘</button></div><div className="jog-settings"><label>Distance<input aria-label="Jog distance mm" type="number" min="0.1" max="10" step="0.1" value={distance} onChange={event=>setDistance(Number(event.target.value))}/><span>mm</span></label><label>Speed<input aria-label="Jog speed mm per minute" type="number" min="1" max="3000" step="100" value={feed} onChange={event=>setFeed(Number(event.target.value))}/><span>mm/min</span></label></div></div>
    <fieldset><legend>Software home</legend><label>X mm<input type="number" min="0" max="400" step="0.1" value={machineHome?.xMm??0} onChange={event=>onSetMachineHome?.({xMm:Number(event.target.value),yMm:machineHome?.yMm??0})}/></label><label>Y mm<input type="number" min="0" max="400" step="0.1" value={machineHome?.yMm??0} onChange={event=>onSetMachineHome?.({xMm:machineHome?.xMm??0,yMm:Number(event.target.value)})}/></label><button aria-label="Go to software home" disabled={!canMove||!validJog} onClick={()=>go({x:machineHome?.xMm??0,y:machineHome?.yMm??0})}>Go home</button></fieldset>
    <section className="saved-positions" aria-label="Saved positions"><div><strong>Start</strong><span>{describe(saved.start)}</span><button aria-label="Set start position" disabled={!machine?.position} onClick={()=>save("start")}>Set</button><button aria-label="Go to start position" disabled={!canMove||!saved.start||!validJog} onClick={()=>go(saved.start)}>Go</button></div><div><strong>End</strong><span>{describe(saved.end)}</span><button aria-label="Set end position" disabled={!machine?.position} onClick={()=>save("end")}>Set</button><button aria-label="Go to end position" disabled={!canMove||!saved.end||!validJog} onClick={()=>go(saved.end)}>Go</button></div></section>
    <p>XY motion only · maximum 10 mm jog and 3000 mm/min · laser output remains blocked.</p>
  </section>;
}
