import { Socket } from "node:net";
import { mkdir,writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";

if(process.env.ATOMBURN_H_DRY_01_APPROVAL!=="approved-by-user")throw new Error("H-DRY-01 is locked without per-run user approval.");
const host="192.168.178.71",port=23;
const allowed=new Set(["M5","$H","$C","G21","G90","G0 X1 Y1","G1 X11 Y1 F300","G1 X11 Y11 F300","G1 X1 Y11 F300","G1 X1 Y1 F300","$J=G91 G21 X10 F300","$J=G91 G21 Y10 F300","$J=G91 G21 X-10 F300","$J=G91 G21 Y-10 F300"]);
let socket,partial="",lines=[],transcript=[];
const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));
async function connect(){socket=new Socket();socket.setNoDelay(true);socket.setTimeout(10000);socket.on("data",data=>{partial+=data.toString("utf8").replaceAll("\0","");const parts=partial.split(/\r?\n/);partial=parts.pop()??"";for(const line of parts.map(v=>v.trim()).filter(Boolean)){lines.push(line);transcript.push(`< ${line}`);}});socket.on("timeout",()=>socket.destroy(new Error("TCP idle timeout")));await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error("TCP connect timeout")),3000);socket.once("error",reject);socket.connect(port,host,()=>{clearTimeout(timer);socket.removeListener("error",reject);resolve();});});transcript.push(`CONNECTED ${host}:${port}`);await wait(300);}
async function close(){if(!socket||socket.destroyed)return;await new Promise(resolve=>{socket.once("close",resolve);socket.end();setTimeout(()=>{socket.destroy();resolve();},500);});}
async function write(value){await new Promise((resolve,reject)=>socket.write(value,error=>error?reject(error):resolve()));}
async function after(start,predicate,timeout,label){const deadline=Date.now()+timeout;while(Date.now()<deadline){const found=lines.slice(start).find(predicate);if(found)return found;if(socket.destroyed)throw new Error(`Connection lost during ${label}.`);await wait(25);}throw new Error(`Timeout during ${label}.`);}
async function send(line,timeout=5000){if(!allowed.has(line)||/M[34]|S[1-9]/.test(line))throw new Error(`Blocked line: ${line}`);const start=lines.length;transcript.push(`> ${line}`);await write(`${line}\n`);const reply=await after(start,value=>value==="ok"||/^error:|^ALARM:|^Grbl\s/i.test(value),timeout,line);if(reply!=="ok")throw new Error(`Controller rejected ${line}: ${reply}`);}
async function status(){const start=lines.length;transcript.push("> ?");await write("?\n");return after(start,value=>value.startsWith("<")&&value.endsWith(">"),3000,"status");}
async function idle(timeout=20000){const deadline=Date.now()+timeout;while(Date.now()<deadline){const value=await status();if(value.startsWith("<Idle|"))return value;if(/^<(Alarm|Door)/.test(value))throw new Error(`Unsafe state: ${value}`);await wait(100);}throw new Error("Machine did not become Idle.");}
function xy(value){const match=/[WM]Pos:([+-]?\d+(?:\.\d+)?),([+-]?\d+(?:\.\d+)?)/.exec(value);if(!match)throw new Error(`Position missing: ${value}`);return[Number(match[1]),Number(match[2])];}
async function home(){await send("M5");await send("$H",60000);const value=await idle();const [x,y]=xy(value);if(x<0||y<0||x>1.1||y>1.1)throw new Error(`Unexpected home pull-off: ${value}`);return value;}
async function report(result,error=""){const root=path.dirname(path.dirname(fileURLToPath(import.meta.url)));const directory=path.join(root,"artifacts","hardware-acceptance");await mkdir(directory,{recursive:true});const stamp=new Date().toISOString().replaceAll(":","-").replaceAll(".","-");const target=path.join(directory,`${stamp}-h-dry-01.json`);await writeFile(target,JSON.stringify({schemaVersion:1,testId:"H-DRY-01",result,error,target:{host,port,connection:"LaserCam TCP",machine:"ATOMSTACK X30 Pro"},protocol:{emission:false,checkMode:true,checkSquareMm:10,laserlessFrameMm:10,feedMmPerMin:300,finalHoming:true},transcript},null,2)+"\n");return target;}

try{await connect();const initial=await status();if(!/^<(Idle|Alarm)\|/.test(initial))throw new Error(`Unexpected initial state: ${initial}`);transcript.push(`HOME ${await home()}`);const before=xy(await status());await send("$C");const check=await status();if(!check.startsWith("<Check|"))throw new Error(`Check mode not confirmed: ${check}`);for(const line of ["M5","G21","G90","G0 X1 Y1","G1 X11 Y1 F300","G1 X11 Y11 F300","G1 X1 Y11 F300","G1 X1 Y1 F300","M5"])await send(line);const checked=await status();if(!checked.startsWith("<Check|"))throw new Error(`Check mode ended unexpectedly: ${checked}`);await send("$C");const exited=await idle();const afterCheck=xy(exited);if(Math.hypot(afterCheck[0]-before[0],afterCheck[1]-before[1])>.05)throw new Error(`Check-mode program moved the machine: ${exited}`);for(const line of ["$J=G91 G21 X10 F300","$J=G91 G21 Y10 F300","$J=G91 G21 X-10 F300","$J=G91 G21 Y-10 F300"]){await send("M5");await send(line);transcript.push(`FRAME ${await idle()}`);}transcript.push(`FINAL-HOME ${await home()}`);await close();const location=await report("passed");console.log(transcript.join("\n"));console.log(`REPORT ${location}`);console.log("RESULT H-DRY-01 PASS");}catch(error){await close().catch(()=>undefined);const message=error instanceof Error?error.message:String(error);const location=await report("failed",message);console.error(transcript.join("\n"));console.error(`REPORT ${location}`);throw error;}
